// <auto-generated />
namespace CU_Baseball_Stat_Modeler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FilledSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FilledSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201701252013025_FilledSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
